-- AlterTable: budget fields on wbs_nodes
ALTER TABLE "wbs_nodes" ADD COLUMN "budgetType" TEXT;
ALTER TABLE "wbs_nodes" ADD COLUMN "unit" TEXT NOT NULL DEFAULT 'szt';
ALTER TABLE "wbs_nodes" ADD COLUMN "unitCost" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "wbs_nodes" ADD COLUMN "quantity" DOUBLE PRECISION NOT NULL DEFAULT 1;
ALTER TABLE "wbs_nodes" ADD COLUMN "totalCost" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "wbs_nodes" ADD COLUMN "margin" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "wbs_nodes" ADD COLUMN "discount" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "wbs_nodes" ADD COLUMN "unitPrice" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "wbs_nodes" ADD COLUMN "totalPrice" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "wbs_nodes" ADD COLUMN "comment" TEXT;
ALTER TABLE "wbs_nodes" ADD COLUMN "phase" TEXT;
