FROM node:18-alpine

WORKDIR /usr/src/app

COPY package*.json ./
COPY prisma ./prisma/

RUN apk add --no-cache openssl
RUN npm install
RUN npx prisma generate

COPY . .

# Push schema, seed roles + users (dev only), start bez watch
CMD ["sh", "-c", "npx prisma db push && node prisma/seed.js && ([ \"$NODE_ENV\" != \"production\" ] && node prisma/seed-users-from-json.js || true) && npm run start"]
